### ISSUE TITLE
NPE in trigger()

### ISSUE THREAD

**Issue by dsrees** [dsrees/JavaPhoenixClient#31]
Received this crash log. Only one instance of it so far, have not done any digging into what could have caused it. Reporting here for a reference

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlin.Triple.getFirst()' on a null object reference
       at org.phoenixframework.PhxChannel.trigger(PhxChannel.kt:337)
       at org.phoenixframework.PhxPush.trigger(PhxPush.kt:191)
       at org.phoenixframework.PhxPush$startTimeout$$inlined$schedule$1.run(Timer.kt:149)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)
```

**Comment by dsrees** [comment]
@dustinconrad We're still on `0.1.3`. I'm assuming updating to `0.1.4` will solve this since, as you mentioned, the refactor doesn't use a `Triple`

**Comment by dsrees** [comment]
👍  I haven't seen it either since updating our project to the new client.
